# Generated by Django 4.1.4 on 2023-01-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='main_category',
        ),
    ]
