# Generated by Django 4.1.4 on 2023-01-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_rename_parent_category_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='Store.category'),
        ),
        migrations.CreateModel(
            name='ProductRelatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prouct_related_image/')),
                ('related_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_img', to='Store.product')),
            ],
        ),
    ]
