# Generated by Django 4.1.5 on 2023-01-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCart', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On delivary', 'Cash On delivary'), ('SSLCommerze', 'SSLCommerze')], max_length=50, null=True),
        ),
    ]
