# Generated by Django 4.1.5 on 2023-01-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCart', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On delivary', 'Cash On delivary'), ('SSLCommerze', 'SSLCommerze')], default='Cash On delivary', max_length=50, null=True),
        ),
    ]
